name: Publish Javadoc

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: gradle
      - name: Grant perms to Gradle executable
      - run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      
